export const LABEL_DEFS = {
  "type:code": ["0e8a16", "Runtime, CLI, script, or behavior change"],
  "type:candidate": ["5319e7", "Case, Candidate, Pattern, Factor, or Artifact contribution"],
  "type:schema": ["1d76db", "Schema, protocol, ontology, or compatibility change"],
  "type:skill-instruction": ["d93f0b", "Agent-facing instruction or skill change"],
  "type:governance": ["b60205", "Governance, template, branch, or maintainer process change"],
  "type:docs": ["0075ca", "Documentation or example change"],
  "type:workflow": ["c5def5", "GitHub workflow or automation change"],
  "type:dependency": ["fbca04", "Dependency or package metadata change"],
  "risk:agent-behavior": ["d73a4a", "May change future agent behavior"],
  "risk:privacy": ["b60205", "May expose private or sensitive evidence"],
  "risk:skill-entry": ["d93f0b", "Touches SKILL.md or scenario skills"],
  "risk:schema-break": ["e11d21", "May break schema compatibility"],
  "risk:workflow": ["e99695", "Touches GitHub Actions or automation"],
  "risk:github-token": ["e11d21", "May affect GitHub token permissions"],
  "risk:dependency": ["fbca04", "Adds or changes dependencies"],
  "risk:file-write": ["d73a4a", "May affect file write behavior"],
  "risk:network": ["d73a4a", "May affect network behavior"],
  "risk:security": ["e11d21", "Security-sensitive change"],
  "risk:governance": ["b60205", "Changes governance rules"],
  "proof:needed": ["e11d21", "Real behavior proof is missing or incomplete"],
  "proof:supplied": ["0e8a16", "Proof fields are present"],
  "proof:sufficient": ["0e8a16", "Maintainer judged proof sufficient"],
  "proof:mock-only": ["fbca04", "Proof appears to rely only on mocks, lint, type checks, or CI"],
  "proof:override": ["5319e7", "Maintainer explicitly overrode proof gate"],
  "candidate:community": ["5319e7", "Community Candidate"],
  "candidate:reviewed": ["0e8a16", "Reviewed Candidate"],
  "candidate:core": ["006b75", "Core Candidate"],
  "candidate:deprecated": ["cfd3d7", "Deprecated Candidate"],
  "candidate:rejected": ["000000", "Rejected Candidate"],
  "candidate:needs-evidence": ["e11d21", "Candidate needs stronger evidence"],
  "candidate:needs-redaction": ["b60205", "Candidate needs redaction before review"],
  "candidate:needs-counterexample": ["fbca04", "Candidate needs counterexamples"],
  "triage:blank-template": ["e11d21", "Template is blank or incomplete"],
  "triage:dirty-pr": ["fbca04", "PR mixes too many surfaces or should be split"],
  "triage:duplicate": ["cfd3d7", "Duplicate issue, PR, or Candidate"],
  "triage:low-signal": ["cfd3d7", "Low-signal contribution"],
  "triage:refactor-only": ["fbca04", "Refactor-only change needs maintainer context"],
  "triage:too-many-prs": ["e11d21", "Author or branch family exceeds queue limits"],
  "triage:rfc-needed": ["d93f0b", "RFC required before review"],
  "triage:owner-only": ["d93f0b", "Owner review required"],
  "triage:manual-only": ["d93f0b", "Manual maintainer handling required"],
  "size:S": ["c2e0c6", "Small PR"],
  "size:M": ["bfdadc", "Medium PR"],
  "size:L": ["f9d0c4", "Large PR"]
};
